name: Update RSS

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - run: pip install feedgen feedparser requests beautifulsoup4

    - run: python main.py

    - run: |
        git config user.name "rss-bot"
        git config user.email "rss@bot.com"
        git add feed.xml
        git commit -m "update feed" || echo "no changes"
        git push
